#include<conio.h>
#include<iostream.h>

void main()
{
clrscr();
cout<<"AAAAAAAAA     ";cout<<"GGGGGGGGG    ";cout<<"UU     UU"<<endl;
cout<<"AAAAAAAAA     ";cout<<"GGGGGGGGG    ";cout<<"UU     UU"<<endl;
cout<<"AA     AA     ";cout<<"GG           ";cout<<"UU     UU"<<endl;
cout<<"AA     AA     ";cout<<"GG  GGGGG    ";cout<<"UU     UU"<<endl;
cout<<"AAAAAAAAA     ";cout<<"GG  GGGGG    ";cout<<"UU     UU"<<endl;
cout<<"AA     AA     ";cout<<"GG     GG    ";cout<<"UU     UU"<<endl;
cout<<"AA     AA     ";cout<<"GGGGGGGGG    ";cout<<"UUUUUUUUU"<<endl;
cout<<"AA     AA     ";cout<<"GGGGGGGGG    ";cout<<"UUUUUUUUU"<<endl;
getch();
}
